package collectors

import (
	"context"
	"fmt"
	"strings"
	"testing"
	"time"

	"github.com/grafana/alloy/internal/agentless"
	"github.com/grafana/alloy/internal/agentless/agentlesstest"
	"github.com/grafana/alloy/internal/agentless/conformance"
	"github.com/prometheus/client_golang/prometheus"
	dto "github.com/prometheus/client_model/go"
	"github.com/stretchr/testify/require"
)

// The sysfs files are unchanged extractions of collector/fixtures/sys.ttar;
// golden.prom is generated by the unchanged default sysfs metric emitter in
// node_exporter v0.18.1-grafana-r01.0.20251024135609-318b01780c89, with procfs
// v0.22.0's sysfs parser. Unlike the e2e script, defaults include dmz/int and
// unknown (-1) speeds. eth0's fixture symlink is materialized without changing
// its contents. All 19 default families are checked; none is omitted. Netlink statistics are opt-in, not netclass's
// default; addr_len and physical-port properties are not exported upstream.
func TestNetclassConformance(t *testing.T) {
	c, err := newNetclassCollector(DefaultConfigs(), nil)
	require.NoError(t, err)
	families := []string{"node_network_up", "node_network_info"}
	for _, spec := range netclassNumbers {
		families = append(families, "node_network_"+spec.family)
	}
	require.Len(t, families, 19)
	conformance.Check(t, conformance.Case{Collector: c, Root: "testdata/netclass", Expected: "testdata/netclass/golden.prom", Families: families})
}

func netclassFixture(t *testing.T) (*netclassCollector, agentless.Input) {
	t.Helper()
	collector, err := newNetclassCollector(DefaultConfigs(), nil)
	require.NoError(t, err)
	c := collector.(*netclassCollector)
	runner, err := agentlesstest.FromFS("testdata/netclass", nil, c.Reads())
	require.NoError(t, err)
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	results, err := runner.Run(ctx, agentless.Target{}, c.Reads())
	require.NoError(t, err)
	in := agentless.Input{}
	for _, result := range results {
		in[result.Read.ID] = result
	}
	reads, err := c.Expand(agentless.Target{}, in)
	require.NoError(t, err)
	results, err = runner.Run(ctx, agentless.Target{}, reads)
	require.NoError(t, err)
	for _, result := range results {
		in[result.Read.ID] = result
	}
	return c, in
}

func TestNetclassRegistrationAndReads(t *testing.T) {
	built, err := Build([]string{"netclass"}, DefaultConfigs(), nil)
	require.NoError(t, err)
	require.Len(t, built, 1)
	require.Equal(t, "netclass", built[0].Name())
	require.NotContains(t, DefaultEnabled(), "netclass")
	found := false
	for _, registration := range Registered() {
		if registration.Name == "netclass" {
			found = true
			require.Equal(t, "linux", registration.OS)
			require.False(t, registration.DefaultEnabled)
		}
	}
	require.True(t, found)
	require.Equal(t, []agentless.Read{agentless.CommandRead("ls", "-1", "/sys/class/net")}, built[0].Reads())
	require.NoError(t, built[0].Reads()[0].Validate())
	c, in := netclassFixture(t)
	reads, err := c.Expand(agentless.Target{}, in)
	require.NoError(t, err)
	require.Len(t, reads, 88)
	seen := map[string]bool{}
	for _, read := range reads {
		require.NoError(t, read.Validate())
		require.Empty(t, read.Argv, "no second listing level")
		require.False(t, seen[read.ID])
		seen[read.ID] = true
	}
}

func TestNetclassListingBoundsAndInvalidNames(t *testing.T) {
	c, in := netclassFixture(t)
	listing := c.Reads()[0]
	in[listing.ID] = agentless.Result{Read: listing, Output: []byte("eth0\nbad name\n../evil\nx/y\n.\nx..y\nx;id\nx\x00y\neth0:1\nbond0\n")}
	reads, err := c.Expand(agentless.Target{}, in)
	require.NoError(t, err)
	require.Len(t, reads, 44)
	for _, read := range reads {
		require.NoError(t, read.Validate())
		require.True(t, strings.HasPrefix(read.Path, "/sys/class/net/eth0/") || strings.HasPrefix(read.Path, "/sys/class/net/bond0/"))
	}
	// The bound is attribute reads, not interfaces: eleven fit, twelve do not.
	for _, count := range []int{11, 12, 257} {
		var output strings.Builder
		for i := 0; i < count; i++ {
			fmt.Fprintf(&output, "eth%d\n", i)
		}
		in[listing.ID] = agentless.Result{Read: listing, Output: []byte(output.String())}
		reads, err := c.Expand(agentless.Target{}, in)
		if count == 11 {
			require.NoError(t, err)
			require.Len(t, reads, 242)
		} else {
			require.ErrorContains(t, err, "expanded read limit")
			require.Nil(t, reads, "reject atomically, never silently truncate")
		}
	}
	for _, output := range []string{"\n", "eth0", "eth0\n\n", "eth0\neth0\n", strings.Repeat("bad name\n", 257), strings.Repeat("x", 1<<20) + "\n"} {
		in[listing.ID] = agentless.Result{Read: listing, Output: []byte(output)}
		reads, err := c.Expand(agentless.Target{}, in)
		require.Error(t, err)
		require.Nil(t, reads)
		ch := make(chan prometheus.Metric, 300)
		require.Error(t, c.Update(agentless.Target{}, in, ch))
		require.Empty(t, ch)
	}
	in[listing.ID] = agentless.Result{Read: listing, Output: []byte(strings.Repeat("bad name\n", 256))}
	reads, err = c.Expand(agentless.Target{}, in)
	require.NoError(t, err)
	require.Empty(t, reads)
}

func netclassMetrics(t *testing.T, c *netclassCollector, in agentless.Input) []*dto.MetricFamily {
	t.Helper()
	reg := prometheus.NewRegistry()
	reg.MustRegister(conformanceNetclass{c: c, in: in})
	families, err := reg.Gather()
	require.NoError(t, err)
	return families
}

type conformanceNetclass struct {
	c  *netclassCollector
	in agentless.Input
}

func (conformanceNetclass) Describe(chan<- *prometheus.Desc) {}
func (c conformanceNetclass) Collect(ch chan<- prometheus.Metric) {
	// Collect executes synchronously for this single collector; report an
	// invalid metric on failure rather than calling FailNow in its goroutine.
	if err := c.c.Update(agentless.Target{}, c.in, ch); err != nil {
		ch <- prometheus.NewInvalidMetric(prometheus.NewDesc("netclass_test_error", "Update failed.", nil, nil), err)
	}
}

func TestNetclassFailedAttributeOnlyOmitsSeries(t *testing.T) {
	for _, failure := range []agentless.Result{{ExitStatus: 1}, {NotExist: true, ExitStatus: 1}, {Truncated: true}, {TimedOut: true}} {
		c, in := netclassFixture(t)
		read := netclassRead("eth0", "speed")
		failure.Read = read
		failure.Output = []byte("1000\n") // Useful-looking output must not leak.
		in[read.ID] = failure
		families := netclassMetrics(t, c, in)
		require.Len(t, families, 19)
		for _, family := range families {
			if family.GetName() == "node_network_speed_bytes" {
				require.Len(t, family.Metric, 3)
				for _, metric := range family.Metric {
					require.NotEqual(t, "eth0", metric.Label[0].GetValue(), "omit only failed attribute series")
				}
			} else {
				require.Len(t, family.Metric, 4, "other interface properties survive")
			}
		}
	}
}

func TestNetclassSpeedAndAdminState(t *testing.T) {
	for _, flags := range []string{"0", "0x1", "0x1003"} {
		c, in := netclassFixture(t)
		speed := netclassRead("eth0", "speed")
		in[speed.ID] = agentless.Result{Read: speed, Output: []byte("-1\n")}
		flag := netclassRead("eth0", "flags")
		in[flag.ID] = agentless.Result{Read: flag, Output: []byte(flags)}
		for _, family := range netclassMetrics(t, c, in) {
			if family.GetName() == "node_network_speed_bytes" {
				found := false
				for _, metric := range family.Metric {
					if metric.Label[0].GetValue() == "eth0" {
						found = true
						require.Equal(t, -125000.0, metric.GetGauge().GetValue())
					}
				}
				require.True(t, found)
			}
			if family.GetName() == "node_network_info" {
				for _, metric := range family.Metric {
					labels := map[string]string{}
					for _, label := range metric.Label {
						labels[label.GetName()] = label.GetValue()
					}
					if labels["device"] == "eth0" {
						want := "up"
						if flags == "0" {
							want = "down"
						}
						require.Equal(t, want, labels["adminstate"])
					}
				}
			}
		}
	}
}

func TestNetclassAttributeBounds(t *testing.T) {
	for _, test := range []struct{ attribute, output string }{
		{"ifalias", strings.Repeat("x", 4097)}, {"address", "\xff"}, {"flags", "bad"}, {"speed", "9223372036854775808"}, {"mtu", strings.Repeat("1", 1<<20)},
	} {
		t.Run(test.attribute, func(t *testing.T) {
			c, in := netclassFixture(t)
			read := netclassRead("eth0", test.attribute)
			in[read.ID] = agentless.Result{Read: read, Output: []byte(test.output)}
			ch := make(chan prometheus.Metric, 300)
			require.Error(t, c.Update(agentless.Target{}, in, ch))
			require.Empty(t, ch, "no retained partial interface metrics")
		})
	}
	c, in := netclassFixture(t)
	read := netclassRead("eth0", "ifalias")
	in[read.ID] = agentless.Result{Read: read, Output: []byte(strings.Repeat("x", 4096))}
	require.Len(t, netclassMetrics(t, c, in), 19)
}

type netclassRecordingRunner struct {
	fake    *agentlesstest.FakeRunner
	batches [][]agentless.Read
}

func (r *netclassRecordingRunner) Run(ctx context.Context, target agentless.Target, reads []agentless.Read) ([]agentless.Result, error) {
	r.batches = append(r.batches, append([]agentless.Read(nil), reads...))
	return r.fake.Run(ctx, target, reads)
}

func TestNetclassScraperIsolation(t *testing.T) {
	cases := map[string]agentless.Result{
		"missing": {NotExist: true, ExitStatus: 1}, "empty": {}, "nonzero": {ExitStatus: 2, Output: []byte("eth0\n")},
		"timeout": {TimedOut: true}, "truncated": {Truncated: true}, "missing timeout": {NotExist: true, TimedOut: true}, "missing truncated": {NotExist: true, Truncated: true},
		"malformed": {Output: []byte("eth0\n\n")}, "over attributes": {Output: []byte("a\nb\nc\nd\ne\nf\ng\nh\ni\nj\nk\nl\n")},
		"over interfaces": {Output: []byte(strings.Repeat("bad name\n", 257))}, "valid and invalid": {Output: []byte("eth0\n../evil\nbad name\n")},
	}
	for name, listingResult := range cases {
		t.Run(name, func(t *testing.T) {
			c, in := netclassFixture(t)
			listing := c.Reads()[0]
			listingResult.Read = listing
			in[listing.ID] = listingResult
			load := &loadavgCollector{}
			lr := load.Reads()[0]
			in[lr.ID] = agentless.Result{Read: lr, Output: []byte("1 2 3 1/1 1\n")}
			runner := &netclassRecordingRunner{fake: &agentlesstest.FakeRunner{Results: in}}
			scraper, err := agentless.NewScraper(runner, []agentless.Collector{c, load}, nil)
			require.NoError(t, err)
			ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
			defer cancel()
			result, err := scraper.Scrape(ctx, agentless.Target{})
			require.NoError(t, err)
			reg := prometheus.NewRegistry()
			reg.MustRegister(result)
			families, err := reg.Gather()
			require.NoError(t, err)
			success := map[string]float64{}
			loadSeen, networkFamilies := false, 0
			for _, family := range families {
				if family.GetName() == "node_load1" {
					loadSeen = true
					require.Equal(t, 1.0, family.Metric[0].GetGauge().GetValue())
				}
				if strings.HasPrefix(family.GetName(), "node_network_") {
					networkFamilies++
					for _, metric := range family.Metric {
						for _, label := range metric.Label {
							if label.GetName() == "device" {
								require.Equal(t, "eth0", label.GetValue())
							}
						}
					}
				}
				if family.GetName() == "node_scrape_collector_success" {
					for _, metric := range family.Metric {
						success[metric.Label[0].GetValue()] = metric.GetGauge().GetValue()
					}
				}
			}
			require.True(t, loadSeen)
			require.Equal(t, 1.0, success["loadavg"])
			want := 0.0
			if name == "missing" || name == "empty" || name == "valid and invalid" {
				want = 1
			}
			require.Equal(t, want, success["netclass"])
			if name == "valid and invalid" {
				require.Equal(t, 19, networkFamilies)
				require.Len(t, runner.batches, 2)
				require.Len(t, runner.batches[1], 22)
				for _, read := range runner.batches[1] {
					require.NoError(t, read.Validate())
					require.True(t, strings.HasPrefix(read.Path, "/sys/class/net/eth0/"))
				}
			} else {
				require.Zero(t, networkFamilies)
				require.Len(t, runner.batches, 1, "rejected reads never reach Runner")
			}
		})
	}
}
